function nazo79(){
  if(document.getElementById('answer79').value=='夢'){
    alert('あたり！');
  }elseif(document.getElementById('answer79').value=='ゆめ'){
    alert('あたり！');
  }elseif(document.getElementById('answer79').value=='ユメ'){
    alert('あたり！');
  }elseif(document.getElementById('answer79').value=='yume'){
    alert('あたり！');
  }elseif(document.getElementById('answer79').value=='YUME'){
    alert('あたり！');
  }elseif(document.getElementById('answer79').value=='dream'){
    alert('あたり！');
  }elseif(document.getElementById('answer79').value=='DREAM'){
    alert('あたり！');
  }
  else{
    alert('はずれ！');}
  }
